// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy8XIG5IUs6GzJNAmsneCddgF2FvWMWFU',
    appId: '1:1033320869267:web:3b8df68325d1a48f3a0c66',
    messagingSenderId: '1033320869267',
    projectId: 'fir-chatg-a995e',
    authDomain: 'fir-chatg-a995e.firebaseapp.com',
    storageBucket: 'fir-chatg-a995e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDig_LXgferl284olQ0pD_IPE07y0PqqR4',
    appId: '1:1033320869267:android:674c1315e56779c53a0c66',
    messagingSenderId: '1033320869267',
    projectId: 'fir-chatg-a995e',
    storageBucket: 'fir-chatg-a995e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD29w6G4KGly6bW-TC57avMMQud6JQFqAU',
    appId: '1:1033320869267:ios:21995230d61542c63a0c66',
    messagingSenderId: '1033320869267',
    projectId: 'fir-chatg-a995e',
    storageBucket: 'fir-chatg-a995e.appspot.com',
    iosClientId: '1033320869267-lhtj8ck4p5bjrg1g0sp5hecpqu0pq1qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
